[theme]
# Primary accent color for interactive elements.
primaryColor = "#3646d3"

# Background color for the main content area.
backgroundColor = "#360c00"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#587558"

# Color used for almost all text.
textColor = "#fafafa"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
